mysql:
  image: mysql:5.7
  container_name: finance-mysql
  env_file:
    - ./mysql/.env
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: finance
    MYSQL_USER: finance
    MYSQL_PASSWORD: finance
  volumes:
    - ./mysql/dbdata:/var/lib/mysql
  ports:
    - "3306:3306"
  restart: always
