version: '3.8'
services:
  postgres:
    image: postgres
    container_name: finance-postgres
    env_file:
      - ./postgres/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    volumes:
      - "./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      - "./postgres/data:/var/lib/postgresql/data"

    ports:
      - "3306:5432"
    restart: always
